# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1330, 883)
        self.WeighTrack = QtWidgets.QLabel(Dialog)
        self.WeighTrack.setGeometry(QtCore.QRect(590, 30, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.WeighTrack.setFont(font)
        self.WeighTrack.setObjectName("WeighTrack")
        self.LoginToYour = QtWidgets.QLabel(Dialog)
        self.LoginToYour.setGeometry(QtCore.QRect(490, 110, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LoginToYour.setFont(font)
        self.LoginToYour.setObjectName("LoginToYour")
        self.usernameLineEdit = QtWidgets.QLineEdit(Dialog)
        self.usernameLineEdit.setGeometry(QtCore.QRect(510, 290, 331, 51))
        self.usernameLineEdit.setStyleSheet("border-radius: 15px;\n"
"border: 2px solid black;")
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(Dialog)
        self.passwordLineEdit.setGeometry(QtCore.QRect(510, 380, 331, 51))
        self.passwordLineEdit.setStyleSheet("border-radius: 15px;\n"
"border: 2px solid black;")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.loginButton = QtWidgets.QPushButton(Dialog)
        self.loginButton.setGeometry(QtCore.QRect(760, 470, 81, 41))
        self.loginButton.setStyleSheet("border-radius: 15px;\n"
"border: 2px solid black;\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.feedbackLabel = QtWidgets.QLabel(Dialog)
        self.feedbackLabel.setGeometry(QtCore.QRect(520, 450, 311, 16))
        self.feedbackLabel.setText("")
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.loginbg = QtWidgets.QLabel(Dialog)
        self.loginbg.setGeometry(QtCore.QRect(300, 210, 791, 421))
        self.loginbg.setStyleSheet("background-color: white;\n"
"border-radius: 15px;\n"
"border: 2px solid black;")
        self.loginbg.setText("")
        self.loginbg.setObjectName("loginbg")
        self.usericon = QtWidgets.QLabel(Dialog)
        self.usericon.setGeometry(QtCore.QRect(460, 290, 41, 41))
        self.usericon.setObjectName("usericon")
        self.passicon = QtWidgets.QLabel(Dialog)
        self.passicon.setGeometry(QtCore.QRect(460, 380, 41, 41))
        self.passicon.setObjectName("passicon")
        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(500, 20, 71, 71))
        self.logo.setStyleSheet("background-image: url(:/newPrefix/logo.png);\n"
"background-image: url(:/newPrefix/icons/logo.png);")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icons/icons/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.loginbg.raise_()
        self.WeighTrack.raise_()
        self.LoginToYour.raise_()
        self.usernameLineEdit.raise_()
        self.passwordLineEdit.raise_()
        self.loginButton.raise_()
        self.feedbackLabel.raise_()
        self.usericon.raise_()
        self.passicon.raise_()
        self.logo.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.WeighTrack.setText(_translate("Dialog", "WeighTrack"))
        self.LoginToYour.setText(_translate("Dialog", "Log In to WeighTrack to Manage your Inventory"))
        self.loginButton.setText(_translate("Dialog", "Log In"))
        self.usericon.setText(_translate("Dialog", "TextLabel"))
        self.passicon.setText(_translate("Dialog", "TextLabel"))
import logo_rc
